apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: q4icubvvi-nodejs 
  janus-idp.io/tekton: q4icubvvi-nodejs
  backstage.io/kubernetes-id: q4icubvvi-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q4icubvvi-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  